lanz/urls.py
from django.urls import path
from . import views

app_name = 'lanz'
urlpatterns = [
    # path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('', views.Url.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
]

lanzino/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lanz/', include('lanz.urls', namespace='lanz')),
    path('account/', include('account.urls', namespace='account')),
]

lanz/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


class PManager(models.Manager):
    def get_queryset(self):
        return super(PManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    published = PManager()
    objects = models.Manager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('lanz:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE, related_name='comments')
    email = models.EmailField()
    name = models.CharField(max_length=255)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'


class Urls(models.Model):
    u1 = models.URLField(max_length=250)
    u2 = models.URLField(max_length=250)
    u3 = models.URLField(max_length=250)
    u4 = models.URLField(max_length=250)

    def __str__(self):
        return self.u1 + self.u2 + self.u3

lanz/forms.py
from django import forms
from .models import Comment


class Send(forms.Form):
    name = forms.CharField(max_length=225)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentF(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

lanz/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.views.generic import ListView
from .forms import Send, CommentF
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        form = Send(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = f"{cd['name']} recommends you read" \
                      f"{post.title}"
            message = f" Read{post.title} at {post_url}\n\n" \
                      f" {cd['name']} s' comments: {cd['comments']}"
            send_mail(subject, message, 'roblineyegon@gmail.com', [cd['to']])
            sent = True
    else:
        form = Send()
    return render(request, 'lanz/post/share.html',
                  {'post': post, 'form': form, 'sent': sent})


def post_list(request):
    object_list = Post.published.all()
    pager = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = pager.page(page)
    except PageNotAnInteger:
        posts = pager.page(1)
    except EmptyPage:
        posts = pager.page(pager.num_pages)
    return render(request, 'lanz/post/list.html',
                  {'posts': posts,
                   "page": page})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None
    comment_form = None
    if request.method == 'POST':
        comment_form = CommentF(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
        else:
            comment_form = CommentF()
    return render(request, 'lanz/post/detail.html',
                  {'post': post, 'comments': comments, 'comment_form': comment_form, 'new_comment': new_comment})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    template_name = 'lanz/post/list.html'
    paginate_by = 3


class Url(ListView):
    template_name = 'lanz/post/list.html'
    queryset = Post.published.all()
    context_object_name = 'posts'

templates/lanz/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/lanz.css'%}" rel="stylesheet">
    <style type="text/css">
        body {
            background-image: url('../../lanz/static/css/stat/image/robby.jpg');
        }
    </style>
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>Powerful predz</h2>
        <p>These are for high stakes.</p>
        <ul id="nav-sidebar">
            <li>{{ ur1 }}</li>
            <li>{{ ur2 }}</li>
            <li>{{ ur3 }}</li>
            <li>{{ ur4 }}</li>
        </ul>
    </div>
</body>
</html>

templates/lanz/post/detail.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    {% extends 'lanz/base.html' %}
    <title>{% block title %} {{ post.title }}{% endblock %}</title>
</head>
<body>
{% block content %}
    <fieldset style="padding-right:0" class="dashboard">
    <h1>{{ post.title }}</h1>
    <p class="date">
    Created {{ post.publish}} by {{ post.author }}
    </p>
    </fieldset>
    <p>
    <a href="{% url "lanz:post_share" post.id %}">Share post</a>
    </p>
    {% with comments.count as total_comments %}
        <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
        {% for comment in comments %}
            <div class="comment">
                <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
                </p>
                {{ comment.body|linebreaks }}
            </div>
        {% empty %}
            <p>No reviews yet.</p>
        {% endfor %}
    {% if new_comment %}
        <h2>Thanks for your review.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}
{% endblock %}

</body>
</html>

templates/lanz/post/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends 'lanz/base.html' %}
    <title>{% block title %} Predz {% endblock %}</title>
</head>
<body>
    {% block content %}
        {% include 'lanz/post/paging.html' with page=page_obj %}
        {% include 'lanz/post/paging.html' with page=posts %}
        <h1>Predz</h1>
        {% for post in posts %}
        <h2>
        <a href="{{ post.get_absolute_url }}"{% load static %}
           >{{ post.title }}</a>
        </h2>
        <h2 >
        <p class="date">
        Published {{ post.publish }}
        </p>
        {{ post.body|truncatewords:30|linebreaks }}
        </h2>
        {% endfor %}
        <p class="tags">Tags: {{ post.tags.all|join:", " }}</p>
    {% endblock %}

</body>
</html>

templates/lanz/post/paging.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'lanz/base.html' %}
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number}}">Previous</a>
        {% endif %}
    </span>
    <span class="current">
        Page {{ page.number }} of {{ page.pager.num_pages }}
    </span>
    <span class="current-app">
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>
</body>
</html>

templates/lanz/post/share.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% extends 'lanz/base.html' %}
    <title>{% block title %}Share post{% endblock %}</title>
</head>
<body>
{% block content %}
    {% if sent %}
        <h1>
        Email successfully sent
        </h1>
        <p>
        "{{ post.title }}"  was sent successfully to {{ form.cleaned_data.to}}
        </p>
     {% else %}
        <h1>Share "{{ post.title }}" by e_--mail
        </h1>
        <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Send Mail">
        </form>
    {% endif %}
{% endblock %}

</body>
</html>